spring:
  application:
    name: catalog-service
  r2dbc:
    url: ${DB_URL:r2dbc:postgresql://localhost:15432/postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}


server:
  port: 8081
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    git:
      mode: full